import { z } from "zod";
import { repositoryManager } from "../runtime/repositories.js";
import { getBudgetStatus, summarizeModelUsage } from "../observability/modelUsage.js";
import { ProjectMcpAdapter, READ_TOOL_ALLOWLIST } from "../projects/projectMcpAdapter.js";
import { getProjectHooks } from "../projects/projectHooks.js";
import { toProjectSummary } from "../projects/projectRegistry.js";
import { getBlobJson, getCmsAgentBlobStore } from "../repository/blobs/blobClient.js";
import type { ExecutionArtifact } from "../workspace/executionTypes.js";
import type { ToolDefinition } from "./toolTypes.js";

const ok = (data: unknown) => ({ ok: true, data });
const anyObj = z.record(z.string(), z.unknown());
const empty = z.object({}).strict();
const id = z.object({ id: z.string().min(1) }).strict();
const runId = z.object({ runId: z.string().min(1).optional() }).strict();
const safeKey = z.string().min(1).max(256).regex(/^[A-Za-z0-9._/-]+$/).refine((k) => !k.includes("..") && !k.startsWith("/"), "Unsafe key");
const blobPrefixes = () => (process.env.TOOL_BLOB_PREFIXES ?? "agent-tools/").split(",").map((p) => p.trim()).filter(Boolean);
const assertPrefix = (key: string) => { if (!blobPrefixes().some((p) => key.startsWith(p))) throw new Error("blob_prefix_not_allowed"); };
const memoryArtifacts = new Map<string, ExecutionArtifact[]>();
const artifactId = () => `artifact_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
const makeTool = (t: ToolDefinition): ToolDefinition => t;
const schema = z.unknown();
const getRunArtifacts = async (rid: string) => [...(await repositoryManager.getArtifactRepository().listArtifacts(rid)), ...(memoryArtifacts.get(rid) ?? [])];
const saveArtifact = (runId: string, artifact: ExecutionArtifact) => memoryArtifacts.set(runId, [...(memoryArtifacts.get(runId) ?? []), artifact]);

async function safeFetch(urlText: string, timeoutMs: number) {
  const url = new URL(urlText);
  if (!["http:", "https:"].includes(url.protocol)) throw new Error("url_protocol_not_allowed");
  if (["localhost", "127.0.0.1", "0.0.0.0", "::1"].includes(url.hostname) || /(^10\.)|(^192\.168\.)|(^172\.(1[6-9]|2\d|3[01])\.)/.test(url.hostname)) throw new Error("private_url_blocked");
  const allow = (process.env.WEB_DOMAIN_ALLOWLIST ?? "").split(",").map((d) => d.trim()).filter(Boolean);
  const deny = (process.env.WEB_DOMAIN_DENYLIST ?? "").split(",").map((d) => d.trim()).filter(Boolean);
  if (allow.length && !allow.some((d) => url.hostname === d || url.hostname.endsWith(`.${d}`))) throw new Error("domain_not_allowed");
  if (deny.some((d) => url.hostname === d || url.hostname.endsWith(`.${d}`))) throw new Error("domain_denied");
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { signal: controller.signal, headers: { accept: "text/html,application/json,text/plain" } });
    const type = res.headers.get("content-type") ?? "";
    if (!/text|json|html|xml/.test(type)) throw new Error("content_type_not_allowed");
    const max = Number(process.env.WEB_RESPONSE_SIZE_LIMIT_BYTES ?? 250000);
    const text = (await res.text()).slice(0, max);
    return { status: res.status, contentType: type, url: res.url, text, truncated: text.length >= max };
  } catch (e) { if (e instanceof Error && e.name === "AbortError") throw new Error("tool_timeout"); throw e; } finally { clearTimeout(timer); }
}

export function createToolRegistry(): ToolDefinition[] {
  const ws = repositoryManager.getWorkspaceRepository();
  const projects = repositoryManager.getProjectRepository();
  const learning = repositoryManager.getLearningRepository();
  return [
    makeTool({ toolId:"workspace.get_node", name:"workspace.get_node", description:"Get one workspace node.", inputSchema:id, outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"workspace", enabled:true, metadata:{}, handler: async (i) => ok({ node: await ws.getNode(id.parse(i).id) ?? null }) }),
    makeTool({ toolId:"workspace.get_nodes", name:"workspace.get_nodes", description:"List workspace nodes.", inputSchema:empty, outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"workspace", enabled:true, metadata:{}, handler: async () => ok({ nodes: await ws.getNodes() }) }),
    makeTool({ toolId:"workspace.get_graph", name:"workspace.get_graph", description:"Get workspace graph.", inputSchema:empty, outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"workspace", enabled:true, metadata:{}, handler: async () => { const nodes = await ws.getNodes(); return ok({ nodes, edges: nodes.flatMap((n) => n.dependsOn.map((d) => ({ from:d, to:n.id }))) }); } }),
    makeTool({ toolId:"stage.get_output", name:"stage.get_output", description:"Get stage output.", inputSchema:id, outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"workspace", enabled:true, metadata:{}, handler: async (i) => ok({ output: await ws.getStageOutput(id.parse(i).id) ?? null }) }),
    makeTool({ toolId:"stage.list_outputs", name:"stage.list_outputs", description:"List stage outputs.", inputSchema:z.object({ stage:z.string().optional() }).strict(), outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"workspace", enabled:true, metadata:{}, handler: async (i) => ok({ outputs: await ws.listStageOutputs(z.object({stage:z.string().optional()}).parse(i).stage) }) }),
    makeTool({ toolId:"stage.save_output", name:"stage.save_output", description:"Save stage output.", inputSchema:z.object({ id:z.string().optional(), stage:z.string().min(1), value:z.unknown() }).strict(), outputSchema:schema, riskLevel:"write", sideEffect:"workspace_write", requiresApproval:true, timeoutMs:2000, category:"workspace", enabled:true, metadata:{}, handler: async (i) => { const d=z.object({id:z.string().optional(),stage:z.string(),value:z.unknown()}).parse(i); return ok({ output: await ws.saveStageOutput(d.stage,d.value,d.id) }); } }),
    makeTool({ toolId:"learning.list_observations", name:"learning.list_observations", description:"List observations.", inputSchema:empty, outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"learning", enabled:true, metadata:{}, handler: async () => ok({ observations: await learning.listObservations() }) }),
    // F4 (T-2, run_1785352838155_l544ye): requiresApproval:true meant this tool was NEVER actually
    // reachable from live node execution — approvedToolIds is only ever populated for the tool.test
    // diagnostic path (see toolResolver.ts's evaluateToolsForNode), never wired into the normal
    // workflow-executor node dispatch (executeRunnableNode never sets it) — so learning_recorder's
    // grant of this tool was denied approval_required on every real run, identically to how
    // project.call_tool stranded contract_intelligence before the read-tool split. Recording an
    // internal, workspace-local observation string never touches a client and never publishes
    // anything, so — unlike an external write — it does not need human gating; riskLevel/sideEffect
    // stay "write"/"workspace_write" (it does mutate the workspace) but requiresApproval is now false.
    // context.runId/nodeId are stamped on every record so it can be joined back to the run that
    // produced it — the existing (pre-fix) observations carry neither field.
    makeTool({ toolId:"learning.record_observation", name:"learning.record_observation", description:"Record observation. Stamped with the recording run/node's id.", inputSchema:z.object({ observation:z.string().min(1), metadata:anyObj.optional() }).strict(), outputSchema:schema, riskLevel:"write", sideEffect:"workspace_write", requiresApproval:false, timeoutMs:2000, category:"learning", enabled:true, metadata:{}, handler: async (i,c) => { const d=z.object({observation:z.string(),metadata:anyObj.optional()}).parse(i); return ok({ observation: await ws.recordObservation(d.observation,d.metadata,{ runId:c.runId, nodeId:c.nodeId }) }); } }),
    makeTool({ toolId:"web.fetch", name:"web.fetch", description:"Fetch text from a validated public URL.", inputSchema:z.object({ url:z.string().url() }).strict(), outputSchema:schema, riskLevel:"read", sideEffect:"external_read", requiresApproval:false, timeoutMs:8000, category:"web", enabled:true, metadata:{ providerEnvVar:"WEB_PROVIDER" }, handler: async (i) => ok({ response: await safeFetch(z.object({url:z.string().url()}).parse(i).url, 8000) }) }),
    makeTool({ toolId:"web.search", name:"web.search", description:"Provider-backed web search.", inputSchema:z.object({ query:z.string().min(1) }).strict(), outputSchema:schema, riskLevel:"read", sideEffect:"external_read", requiresApproval:false, timeoutMs:8000, category:"web", enabled:true, metadata:{}, handler: async (i) => ok({ provider: process.env.WEB_PROVIDER ?? "disabled", results: [], query: z.object({query:z.string()}).parse(i).query }) }),
    ...["file.list","file.get_metadata","file.read_text","file.save_text","file.delete"].map((name) => makeTool({ toolId:name, name, description:"Workspace-managed file operation backed by artifacts.", inputSchema:z.object({ path:safeKey.optional(), text:z.string().optional() }).strict(), outputSchema:schema, riskLevel:name.includes("save")||name.includes("delete")?"write":"read", sideEffect:name.includes("save")||name.includes("delete")?"workspace_write":"none", requiresApproval:name.includes("save")||name.includes("delete"), timeoutMs:2000, category:"files", enabled:true, metadata:{}, handler: async (i,c) => { const d=z.object({path:safeKey.optional(),text:z.string().optional()}).parse(i); if (d.path) assertPrefix(`agent-tools/files/${d.path}`); const arts=await getRunArtifacts(c.runId); if (name==="file.list") return ok({ files: arts.filter(a=>a.type==="file.text").map(a=>({ path:a.id, createdAt:a.createdAt })) }); if (name==="file.save_text") { const a={id:d.path!,nodeId:c.nodeId,type:"file.text",value:d.text??"",createdAt:new Date().toISOString()}; saveArtifact(c.runId,a); return ok({ saved:true, file:a }); } const found=arts.find(a=>a.id===d.path); if (name==="file.delete") return ok({ deleted:Boolean(found) }); return ok(name==="file.get_metadata" ? { metadata: found ? { path:found.id, type:found.type, createdAt:found.createdAt } : null } : { text: typeof found?.value === "string" ? found.value : null }); } })),
    ...["artifact.list","artifact.get","artifact.save_json","artifact.save_text"].map((name) => makeTool({ toolId:name, name, description:"Run artifact operation.", inputSchema:z.object({ artifactId:z.string().optional(), value:z.unknown().optional(), text:z.string().optional(), type:z.string().optional() }).strict(), outputSchema:schema, riskLevel:name.includes("save")?"write":"read", sideEffect:name.includes("save")?"workspace_write":"none", requiresApproval:name.includes("save"), timeoutMs:2000, category:"artifacts", enabled:true, metadata:{}, handler: async (i,c) => { const d=z.object({artifactId:z.string().optional(),value:z.unknown().optional(),text:z.string().optional(),type:z.string().optional()}).parse(i); const arts=await getRunArtifacts(c.runId); if (name==="artifact.list") return ok({ artifacts: arts }); if (name==="artifact.get") return ok({ artifact: arts.find(a=>a.id===d.artifactId) ?? null }); const a={ id:d.artifactId ?? artifactId(), nodeId:c.nodeId, type:d.type ?? (name.endsWith("text")?"text":"json"), value:name.endsWith("text")?d.text:d.value, createdAt:new Date().toISOString() }; saveArtifact(c.runId,a); return ok({ artifact:a }); } })),
    ...["blob.list","blob.get_json","blob.put_json","blob.delete"].map((name) => makeTool({ toolId:name, name, description:"Safe logical blob operation restricted by configured prefixes.", inputSchema:z.object({ key:safeKey.optional(), prefix:safeKey.optional(), value:z.unknown().optional() }).strict(), outputSchema:schema, riskLevel:name.includes("put")||name.includes("delete")?"write":"read", sideEffect:name.includes("put")||name.includes("delete")?"workspace_write":"none", requiresApproval:name.includes("put")||name.includes("delete"), timeoutMs:4000, category:"blobs", enabled:true, metadata:{ prefixes: blobPrefixes() }, handler: async (i) => { const d=z.object({key:safeKey.optional(),prefix:safeKey.optional(),value:z.unknown().optional()}).parse(i); if (d.key) assertPrefix(d.key); if (d.prefix) assertPrefix(d.prefix); const store=getCmsAgentBlobStore(); if (name==="blob.list") return ok(await store.list({ prefix:d.prefix ?? blobPrefixes()[0] })); if (name==="blob.get_json") return ok({ value: await getBlobJson(store,d.key!) }); if (name==="blob.put_json") { await store.setJSON(d.key!, d.value); return ok({ saved:true }); } await store.delete(d.key!); return ok({ deleted:true }); } })),
    makeTool({ toolId:"project.list", name:"project.list", description:"List projects.", inputSchema:empty, outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"project_mcp", enabled:true, metadata:{}, handler: async () => ok({ projects:(await projects.list()).map((p)=>toProjectSummary(p)) }) }),
    makeTool({ toolId:"project.get", name:"project.get", description:"Get project.", inputSchema:z.object({projectId:z.string()}).strict(), outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"project_mcp", enabled:true, metadata:{}, handler: async (i) => { const p=await projects.get(z.object({projectId:z.string()}).parse(i).projectId); return ok({ project:p?toProjectSummary(p):null }); } }),
    ...["project.test_connection","project.list_tools","project.call_tool"].map((name)=>makeTool({ toolId:name, name, description:"Guarded project MCP operation.", inputSchema:z.object({ projectId:z.string(), tool:z.string().optional(), arguments:anyObj.optional() }).strict(), outputSchema:schema, riskLevel:name==="project.call_tool"?"write":"read", sideEffect:name==="project.call_tool"?"external_write":"external_read", requiresApproval:name==="project.call_tool", timeoutMs:8000, category:"project_mcp", enabled:true, metadata:{}, handler: async(i)=>{ const d=z.object({projectId:z.string(),tool:z.string().optional(),arguments:anyObj.optional()}).parse(i); const p=await projects.get(d.projectId); if(!p) throw new Error("unknown_project"); const a=new ProjectMcpAdapter(p); return ok(name==="project.test_connection"? await a.testConnection() : name==="project.list_tools"? await a.listTools() : { call: await a.callTool(d.tool!, d.arguments ?? {}) }); } })),
    // Read-only split of project.call_tool (see projectMcpAdapter.ts for why): riskLevel "read",
    // requiresApproval FALSE, so a node's effective-tools resolution never drops it for lack of an
    // approval context — that drop is exactly what stranded contract_intelligence in T-2. Permitted
    // operations are the fixed, server-side READ_TOOL_ALLOWLIST; anything else is refused by
    // callReadTool before any transport. project.call_tool above is untouched: still write,
    // requiresApproval true, the only path to an external write.
    makeTool({ toolId:"project.call_read_tool", name:"project.call_read_tool", description:`Call a read-only tool on a registered project MCP server, without approval. Permitted operations are a fixed, server-side allowlist (${READ_TOOL_ALLOWLIST.join(", ")}) — never caller-supplied; anything else is refused before any transport with code "read_tool_operation_not_permitted". Still honors the project's own toolPolicies/defaultToolPolicy and the executable project policy (legacy artifact fallback blocks) — a project can still block a read op. Use project.call_tool for writes.`, inputSchema:z.object({ projectId:z.string(), tool:z.string().min(1), arguments:anyObj.optional() }).strict(), outputSchema:schema, riskLevel:"read", sideEffect:"external_read", requiresApproval:false, timeoutMs:8000, category:"project_mcp", enabled:true, metadata:{}, handler: async(i)=>{ const d=z.object({projectId:z.string(),tool:z.string().min(1),arguments:anyObj.optional()}).parse(i); const p=await projects.get(d.projectId); if(!p) throw new Error("unknown_project"); const a=new ProjectMcpAdapter(p); const policyFindings=getProjectHooks(d.projectId)?.enforceCallToolPolicy?.({ tool:d.tool, arguments:d.arguments }) ?? []; const blocking=policyFindings.filter((finding)=>finding.severity==="error"); if(blocking.length) return ok({ call:{ ok:false, projectId:d.projectId, connection:a.connectionState(), tool:d.tool, permission:"blocked" as const, blockedByPolicy:true, policyFindings:blocking, error:`Blocked by executable project policy: ${blocking.map((finding)=>finding.code).join(", ")}` } }); return ok({ call: await a.callReadTool(d.tool, d.arguments ?? {}) }); } }),
    makeTool({ toolId:"repository.get_health", name:"repository.get_health", description:"Repository health.", inputSchema:empty, outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"diagnostics", enabled:true, metadata:{}, handler: async()=>ok({ health: await repositoryManager.getRepositoryHealth() }) }),
    makeTool({ toolId:"usage.get_summary", name:"usage.get_summary", description:"Usage summary.", inputSchema:runId, outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"usage", enabled:true, metadata:{}, handler: async(i)=>ok({ summary: await summarizeModelUsage(runId.parse(i)) }) }),
    makeTool({ toolId:"usage.get_budget_status", name:"usage.get_budget_status", description:"Budget status.", inputSchema:z.object({projectId:z.string().optional(),runId:z.string().optional(),budgetUsd:z.number().optional()}).strict(), outputSchema:schema, riskLevel:"read", sideEffect:"none", requiresApproval:false, timeoutMs:2000, category:"usage", enabled:true, metadata:{}, handler: async(i)=>ok({ budgetStatus: await getBudgetStatus(z.object({projectId:z.string().optional(),runId:z.string().optional(),budgetUsd:z.number().optional()}).parse(i)) }) })
  ];
}
