// T13.4 CONFORMANCE FIXTURE — the platform's REAL JSON Schemas for the object-substrate MCP tools
// src/agent/capture/cloneEngine.ts calls through callProjectTool.
//
// PROVENANCE, AND A DEVIATION FROM THE SPEC WORTH FLAGGING:
//
// T13.4-SPEC.md's instruction was "the schemas are committed at docs/mcp-tool-manifest.json (the
// two-plane drift lock) — read them from there, do not hand-copy them." That file does NOT hold
// these schemas. It is generated by scripts/twoPlaneDrift.ts to lock CMS-Agent's OWN served tool
// surface — workspace_*, project_*, agent_*, node_*, and 145 others CMS-Agent itself exposes over
// its Netlify and Cloud-Run planes — against each other; each entry carries only an
// `inputSchemaHash` (a sha256 of the schema, for drift comparison), never the schema body, and the
// object-substrate verbs this module translates (object_checkout, object_create, object_patch, ...)
// do not appear in it at all: they are the PLATFORM's remote surface, reached through
// project.call_tool at runtime (src/agent/projects/projectMcpAdapter.ts), never a tool CMS-Agent
// serves itself. Nothing in this repository vendors the platform's remote tool schemas as a
// committed, generated file the way docs/mcp-tool-manifest.json does for CMS-Agent's own surface —
// see the T13.4 implementation report for this finding in full.
//
// Given that, the schemas below were captured from the actual live platform MCP connector's
// `tools/list` surface reachable from this working environment (connector "Kugel-Platform" — the
// same object-substrate surface src/agent/projects/platform/definition.ts's PLATFORM_TOOL_POLICIES
// names) on 2026-08-24, and are pasted here VERBATIM — copied, not retyped from memory or from this
// module's own comments, and not paraphrased. This is the closest available thing to "the real
// schema" the instruction asked for; it is a live capture rather than a byte-identical read of a
// committed file, which is the deviation being flagged rather than silently papered over.
//
// If a future round wants this locked the way docs/mcp-tool-manifest.json locks CMS-Agent's own
// surface, the fix is upstream of this file: the platform repo would need to commit and version its
// OWN tool manifest (mirroring scripts/twoPlaneDrift.ts's approach) for cms-agent to read
// mechanically instead of re-capturing by hand.

// ─────────────────────────────────────────────────────────────────────────────────────────────────
// STALENESS GUARD METADATA (read by tests/agent/capture/mcpBoundaryConformance.test.ts).
//
// CAPTURED:     2026-08-24
// SOURCE:       the live platform MCP connector's `tools/list` response (connector "Kugel-Platform"
//               in the working environment this fixture was captured from — the same object-
//               substrate surface src/agent/projects/platform/definition.ts's PLATFORM_TOOL_POLICIES
//               names), NOT docs/mcp-tool-manifest.json — see the provenance note above for why that
//               file cannot supply these.
// RE-CAPTURE:   connect an MCP client to the platform connector, call tools/list, and for every tool
//               in TOOL_WIRE_SPECS (src/agent/capture/mcpBoundary.ts) that is new, changed, or
//               missing here, paste its schema into PLATFORM_TOOL_SCHEMAS below VERBATIM — copied,
//               never hand-typed or paraphrased — then update PLATFORM_TOOL_SCHEMAS_CAPTURED_AT.
//
// This is a point-in-time capture, not a generated, drift-locked artifact — nothing regenerates it
// automatically the way `npm run drift:update` regenerates docs/mcp-tool-manifest.json. Left alone,
// that goes stale exactly the way this whole T13.4 effort exists to stop: a schema drifts, nobody
// notices, and the conformance test keeps passing against a copy that no longer describes the real
// tool. The one piece of drift this file's own staleness-guard test CAN catch without a live fetch —
// mcpBoundary.ts routing a tool this file has never captured at all — fails loudly instead:
// see "fixture staleness guard" in mcpBoundaryConformance.test.ts. It cannot detect an EXISTING
// entry's schema silently changing on the platform side; that class of drift still needs a human to
// re-run the RE-CAPTURE step above periodically or when a platform change is suspected.
export const PLATFORM_TOOL_SCHEMAS_CAPTURED_AT = "2026-08-24";
export const PLATFORM_TOOL_SCHEMAS_SOURCE = 'the live platform MCP connector\'s tools/list (connector "Kugel-Platform")';
export const PLATFORM_TOOL_SCHEMAS_RECAPTURE_INSTRUCTION =
  "Re-capture: call tools/list against the platform MCP connector, copy the missing/changed tool's schema verbatim (no hand-typing, no paraphrase) into PLATFORM_TOOL_SCHEMAS in tests/agent/capture/fixtures/platformToolSchemas.ts, and update PLATFORM_TOOL_SCHEMAS_CAPTURED_AT.";

export const PLATFORM_TOOL_SCHEMAS: Record<string, unknown> = {
  object_checkout: {
    additionalProperties: false,
    properties: {
      lease_seconds: { description: "Optional lease seconds (default 900, max 3600).", minimum: 0, type: "integer" },
      object_id: { minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      }
    },
    required: ["object_type", "object_id"],
    type: "object"
  },
  object_create: {
    additionalProperties: false,
    properties: {
      agent_name: { description: "Optional self-declared agent name recorded on history (attribution only).", minLength: 1, type: "string" },
      body: { additionalProperties: true, description: "The per-type object body; validated server-side against the T0.2 schema.", type: "object" },
      idempotency_key: { description: "Optional client-supplied key for safe retries.", minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      },
      requested_id: { description: "Optional explicit object id; a valid id is minted from the body when omitted.", minLength: 1, type: "string" },
      site: { description: "Owning site object id, e.g. site_acme.", minLength: 1, type: "string" }
    },
    required: ["object_type", "site", "body"],
    type: "object"
  },
  object_checkin: {
    additionalProperties: false,
    properties: {
      lock_token: { minLength: 1, type: "string" },
      object_id: { minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      }
    },
    required: ["object_type", "object_id", "lock_token"],
    type: "object"
  },
  object_patch: {
    additionalProperties: false,
    properties: {
      expected_record_version: { description: "The record version you last read (optimistic concurrency check).", minimum: 0, type: "integer" },
      lock_token: { minLength: 1, type: "string" },
      object_id: { minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      },
      ops: { description: "Array of typed patch ops (the C§2.0 grammar).", items: { additionalProperties: true, type: "object" }, type: "array" }
    },
    required: ["object_type", "object_id", "lock_token", "expected_record_version", "ops"],
    type: "object"
  },
  object_get: {
    additionalProperties: false,
    properties: {
      object_id: { description: "The object id, e.g. page_home.", minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      }
    },
    required: ["object_type", "object_id"],
    type: "object"
  },
  object_inventory: {
    additionalProperties: false,
    properties: {
      object_id: { description: "With object_type: return the single-object detail view instead of a list.", minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      },
      pending_changes: { description: "Optional: true → only objects the live site has not seen; false → only fully published ones.", type: "boolean" },
      requires_approval: { description: "Optional filter: true → only approval-gated types; false → only autonomous ones.", type: "boolean" },
      review_state: { description: "Optional review-state filter (none = no review has ever been opened).", enum: ["none", "open", "changes_requested", "approved"], type: "string" },
      status: { description: "Optional status filter.", enum: ["active", "archived"], type: "string" }
    },
    required: [],
    type: "object"
  },
  registry_get: {
    additionalProperties: false,
    properties: { registry: { description: "Optional registry name.", enum: ["component", "page_type"], type: "string" } },
    required: [],
    type: "object"
  },
  site_apply_theme: {
    additionalProperties: false,
    properties: {
      agent_name: { description: "Optional self-declared agent name recorded on history (attribution only).", minLength: 1, type: "string" },
      dry_run: { description: "true → return the computed set_site_brand_tokens op and validation; persist nothing (no lock).", type: "boolean" },
      expected_record_version: { description: "The record_version your checkout returned; dry_run needs none.", minimum: 0, type: "integer" },
      lock_token: { description: "Your held site lock (from object_checkout on the site object); dry_run needs none.", minLength: 1, type: "string" },
      site_id: { description: "The site singleton object id, e.g. site_acme.", minLength: 1, type: "string" },
      theme_id: { description: "The theme object id, e.g. thm_acme_default.", minLength: 1, type: "string" }
    },
    required: ["theme_id", "site_id"],
    type: "object"
  }
};
