// T13.4 CONFORMANCE FIXTURE — the platform's REAL JSON Schemas for the object-substrate MCP tools
// src/agent/capture/cloneEngine.ts calls through callProjectTool.
//
// PROVENANCE, AND A DEVIATION FROM THE SPEC WORTH FLAGGING:
//
// T13.4-SPEC.md's instruction was "the schemas are committed at docs/mcp-tool-manifest.json (the
// two-plane drift lock) — read them from there, do not hand-copy them." That file does NOT hold
// these schemas. It is generated by scripts/twoPlaneDrift.ts to lock CMS-Agent's OWN served tool
// surface — workspace_*, project_*, agent_*, node_*, and 145 others CMS-Agent itself exposes over
// its Netlify and Cloud-Run planes — against each other; each entry carries only an
// `inputSchemaHash` (a sha256 of the schema, for drift comparison), never the schema body, and the
// object-substrate verbs this module translates (object_checkout, object_create, object_patch, ...)
// do not appear in it at all: they are the PLATFORM's remote surface, reached through
// project.call_tool at runtime (src/agent/projects/projectMcpAdapter.ts), never a tool CMS-Agent
// serves itself. Nothing in this repository vendors the platform's remote tool schemas as a
// committed, generated file the way docs/mcp-tool-manifest.json does for CMS-Agent's own surface —
// see the T13.4 implementation report for this finding in full.
//
// Given that, the schemas below were captured from the actual live platform MCP connector's
// `tools/list` surface reachable from this working environment (connector "Kugel-Platform" — the
// same object-substrate surface src/agent/projects/platform/definition.ts's PLATFORM_TOOL_POLICIES
// names) on 2026-08-24, and are pasted here VERBATIM — copied, not retyped from memory or from this
// module's own comments, and not paraphrased. This is the closest available thing to "the real
// schema" the instruction asked for; it is a live capture rather than a byte-identical read of a
// committed file, which is the deviation being flagged rather than silently papered over.
//
// If a future round wants this locked the way docs/mcp-tool-manifest.json locks CMS-Agent's own
// surface, the fix is upstream of this file: the platform repo would need to commit and version its
// OWN tool manifest (mirroring scripts/twoPlaneDrift.ts's approach) for cms-agent to read
// mechanically instead of re-capturing by hand.

// ───────────────────────────────────────────────────────────────────────────────────────────────────────
// STALENESS GUARD METADATA (read by tests/agent/capture/mcpBoundaryConformance.test.ts).
//
// CAPTURED:     2026-08-24
// SOURCE:       the live platform MCP connector's `tools/list` response (connector "Kugel-Platform"
//               in the working environment this fixture was captured from — the same object-
//               substrate surface src/agent/projects/platform/definition.ts's PLATFORM_TOOL_POLICIES
//               names), NOT docs/mcp-tool-manifest.json — see the provenance note above for why that
//               file cannot supply these.
// RE-CAPTURE:   connect an MCP client to the platform connector, call tools/list, and for every tool
//               in TOOL_WIRE_SPECS (src/agent/capture/mcpBoundary.ts) that is new, changed, or
//               missing here, paste its schema into PLATFORM_TOOL_SCHEMAS below VERBATIM — copied,
//               never hand-typed or paraphrased — then update PLATFORM_TOOL_SCHEMAS_CAPTURED_AT.
//
// This is a point-in-time capture, not a generated, drift-locked artifact — nothing regenerates it
// automatically the way `npm run drift:update` regenerates docs/mcp-tool-manifest.json. Left alone,
// that goes stale exactly the way this whole T13.4 effort exists to stop: a schema drifts, nobody
// notices, and the conformance test keeps passing against a copy that no longer describes the real
// tool. The one piece of drift this file's own staleness-guard test CAN catch without a live fetch —
// mcpBoundary.ts routing a tool this file has never captured at all — fails loudly instead:
// see "fixture staleness guard" in mcpBoundaryConformance.test.ts. It cannot detect an EXISTING
// entry's schema silently changing on the platform side; that class of drift still needs a human to
// re-run the RE-CAPTURE step above periodically or when a platform change is suspected.
export const PLATFORM_TOOL_SCHEMAS_CAPTURED_AT = "2026-08-24";
export const PLATFORM_TOOL_SCHEMAS_SOURCE = 'the live platform MCP connector\'s tools/list (connector "Kugel-Platform")';
export const PLATFORM_TOOL_SCHEMAS_RECAPTURE_INSTRUCTION =
  "Re-capture: call tools/list against the platform MCP connector, copy the missing/changed tool's schema verbatim (no hand-typing, no paraphrase) into PLATFORM_TOOL_SCHEMAS in tests/agent/capture/fixtures/platformToolSchemas.ts, and update PLATFORM_TOOL_SCHEMAS_CAPTURED_AT.";

export const PLATFORM_TOOL_SCHEMAS: Record<string, unknown> = {
  object_checkout: {
    additionalProperties: false,
    properties: {
      lease_seconds: { description: "Optional lease seconds (default 900, max 3600).", minimum: 0, type: "integer" },
      object_id: { minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      }
    },
    required: ["object_type", "object_id"],
    type: "object"
  },
  object_create: {
    additionalProperties: false,
    properties: {
      agent_name: { description: "Optional self-declared agent name recorded on history (attribution only).", minLength: 1, type: "string" },
      body: { additionalProperties: true, description: "The per-type object body; validated server-side against the T0.2 schema.", type: "object" },
      idempotency_key: { description: "Optional client-supplied key for safe retries.", minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      },
      requested_id: { description: "Optional explicit object id; a valid id is minted from the body when omitted.", minLength: 1, type: "string" },
      site: { description: "Owning site object id, e.g. site_acme.", minLength: 1, type: "string" }
    },
    required: ["object_type", "site", "body"],
    type: "object"
  },
  object_checkin: {
    additionalProperties: false,
    properties: {
      lock_token: { minLength: 1, type: "string" },
      object_id: { minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      }
    },
    required: ["object_type", "object_id", "lock_token"],
    type: "object"
  },
  object_patch: {
    additionalProperties: false,
    properties: {
      expected_record_version: { description: "The record version you last read (optimistic concurrency check).", minimum: 0, type: "integer" },
      lock_token: { minLength: 1, type: "string" },
      object_id: { minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      },
      ops: { description: "Array of typed patch ops (the C§2.0 grammar).", items: { additionalProperties: true, type: "object" }, type: "array" }
    },
    required: ["object_type", "object_id", "lock_token", "expected_record_version", "ops"],
    type: "object"
  },
  object_get: {
    additionalProperties: false,
    properties: {
      object_id: { description: "The object id, e.g. page_home.", minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      }
    },
    required: ["object_type", "object_id"],
    type: "object"
  },
  object_inventory: {
    additionalProperties: false,
    properties: {
      object_id: { description: "With object_type: return the single-object detail view instead of a list.", minLength: 1, type: "string" },
      object_type: {
        description: "CMS object type.",
        enum: ["page", "section", "navigation", "taxonomy", "site", "template", "section_template", "theme", "product", "content_item", "tracking_config", "editorial_voice"],
        type: "string"
      },
      pending_changes: { description: "Optional: true → only objects the live site has not seen; false → only fully published ones.", type: "boolean" },
      requires_approval: { description: "Optional filter: true → only approval-gated types; false → only autonomous ones.", type: "boolean" },
      review_state: { description: "Optional review-state filter (none = no review has ever been opened).", enum: ["none", "open", "changes_requested", "approved"], type: "string" },
      status: { description: "Optional status filter.", enum: ["active", "archived"], type: "string" }
    },
    required: [],
    type: "object"
  },
  registry_get: {
    additionalProperties: false,
    properties: { registry: { description: "Optional registry name.", enum: ["component", "page_type"], type: "string" } },
    required: [],
    type: "object"
  },
  site_apply_theme: {
    additionalProperties: false,
    properties: {
      agent_name: { description: "Optional self-declared agent name recorded on history (attribution only).", minLength: 1, type: "string" },
      dry_run: { description: "true → return the computed set_site_brand_tokens op and validation; persist nothing (no lock).", type: "boolean" },
      expected_record_version: { description: "The record_version your checkout returned; dry_run needs none.", minimum: 0, type: "integer" },
      lock_token: { description: "Your held site lock (from object_checkout on the site object); dry_run needs none.", minLength: 1, type: "string" },
      site_id: { description: "The site singleton object id, e.g. site_acme.", minLength: 1, type: "string" },
      theme_id: { description: "The theme object id, e.g. thm_acme_default.", minLength: 1, type: "string" }
    },
    required: ["theme_id", "site_id"],
    type: "object"
  },
  // T15.34 (#210; ADR-2026-08-25-structure-studio §7) — the pdf-tool bridge's four verbs
  // pdfTemplateEngine.ts's callProjectTool reaches. DIFFERENT PROVENANCE from the eight entries
  // above: those were captured from the platform's own object-substrate MCP connector
  // ("Kugel-Platform"); these four were captured live, VERBATIM (copied, not retyped or
  // paraphrased), from a tenant's own connected MCP surface (site "Dr_Lurie_Skincare") on
  // 2026-08-25 — the same trusted Platform bridge in front of pdf-tool's pdf-template-store that
  // ADR §7 charters the studio to call. PLATFORM_TOOL_SCHEMAS_CAPTURED_AT above is left untouched
  // (it still honestly describes only the eight object-substrate entries); these four carry their
  // own capture date in this comment instead, per the same re-capture discipline the header above
  // documents.
  create_pdf_template: {
    additionalProperties: false,
    properties: {
      idempotency_key: { description: "Optional client-supplied key for safe retries. Pass the SAME value on a retry of this exact call (e.g. after a timeout or 502) to get back the ORIGINAL result instead of causing a duplicate write. Example: pass \"publish-article-42-attempt\" on both the first call and any retry. Omit to run the write fresh every time (previous behavior).", minLength: 1, type: "string" },
      label: { description: "Optional human-readable label.", minLength: 1, type: "string" },
      renderer: { description: "Rendering engine, pinned for the template's life. Omit to default to pdfme.", enum: ["pdfme", "react-pdf", "typst", "chromium"], type: "string" },
      site_id: { description: "Owning site object id, e.g. site_acme. Must match this deployment.", minLength: 1, type: "string" },
      tags: { description: "Optional list of tags.", items: { minLength: 1, type: "string" }, type: "array" },
      template_id: { description: "Optional existing template id to version instead of creating a new template.", minLength: 1, type: "string" },
      template_json: { additionalProperties: true, description: "The pdf-tool template definition for the chosen renderer.", type: "object" }
    },
    required: ["site_id", "template_json"],
    type: "object"
  },
  validate_pdf_template: {
    additionalProperties: false,
    properties: {
      data: { additionalProperties: true, description: "Required worst-case sample data for the validation render, forwarded verbatim to pdf-tool. pdf-tool renders the template against this data during validation, so it should exercise the template's longest/edge-case field values, not typical data.", type: "object" },
      site_id: { description: "Owning site object id; must match this deployment.", minLength: 1, type: "string" },
      template_id: { description: "The template object id to validate.", minLength: 1, type: "string" },
      version: { description: "Optional specific version to validate; omit for the latest draft version.", minimum: 0, type: "integer" }
    },
    required: ["site_id", "template_id", "data"],
    type: "object"
  },
  get_pdf_template_validation: {
    additionalProperties: false,
    properties: {
      site_id: { description: "Owning site object id; must match this deployment.", minLength: 1, type: "string" },
      template_id: { description: "The template object id.", minLength: 1, type: "string" },
      validation_id: { description: "Optional specific validationId from validate_pdf_template; omit for the latest.", minLength: 1, type: "string" },
      version: { description: "Optional specific version; omit for the latest/active version.", minimum: 0, type: "integer" }
    },
    required: ["site_id", "template_id"],
    type: "object"
  },
  publish_pdf_template: {
    additionalProperties: false,
    properties: {
      site_id: { description: "Owning site object id; must match this deployment.", minLength: 1, type: "string" },
      template_id: { description: "The template object id to publish.", minLength: 1, type: "string" },
      version: { description: "Optional specific version to publish; omit for the latest draft version.", minimum: 0, type: "integer" }
    },
    required: ["site_id", "template_id"],
    type: "object"
  },

  // ─────────────────────────────────────────────────────────────────────────────────────────────────
  // SECOND CAPTURE — 2026-09-15, same provenance as the block above: the live platform MCP
  // connector's own tools/list (connector "Kugel-Platform"), pasted verbatim, not retyped from
  // memory and not paraphrased. These four are the verbs Milestone A remainder runner 3a's
  // production wiring (imageTemplateRevisionPlatformProviders.ts) speaks. Descriptions are elided
  // (the conformance checker reads type/required/enum/minLength/minimum/additionalProperties only,
  // and the real descriptions run to several hundred words each) — every SHAPE field is verbatim.
  preview_pdf_template_fixture: {
    additionalProperties: false,
    properties: {
      fixture: { enum: ["long", "short", "empty", "rich_text", "rtl", "images"], type: "string" },
      idempotency_key: { minLength: 1, type: "string" },
      renderer: { enum: ["pdfme", "react-pdf", "typst", "chromium"], type: "string" },
      site_id: { minLength: 1, type: "string" },
      template_id: { minLength: 1, type: "string" },
      template_json: { additionalProperties: true, type: "object" },
      version: { minimum: 0, type: "integer" }
    },
    required: ["site_id", "template_id", "template_json", "fixture"],
    type: "object"
  },
  verify_pdf_content: {
    additionalProperties: false,
    properties: {
      artifactReference: {
        additionalProperties: false,
        properties: { blobKey: { type: "string" }, sha256: { type: "string" } },
        type: "object"
      },
      requirements: {
        additionalProperties: false,
        properties: { maxBytes: { minimum: 1, type: "integer" }, minPageCount: { minimum: 1, type: "integer" } },
        type: "object"
      },
      site_id: { minLength: 1, type: "string" },
      url: { minLength: 1, type: "string" }
    },
    required: ["site_id"],
    type: "object"
  },
  search_artifacts: {
    additionalProperties: false,
    properties: {
      createdAfter: { format: "date-time", type: "string" },
      createdBefore: { format: "date-time", type: "string" },
      cursor: { minLength: 1, type: "string" },
      includeDeleted: { type: "boolean" },
      limit: { maximum: 100, minimum: 1, type: "integer" },
      tag: { maxLength: 40, minLength: 1, type: "string" }
    },
    required: [],
    type: "object"
  },
  get_artifact_metadata: {
    additionalProperties: false,
    properties: {
      requestId: { minLength: 1, type: "string" },
      sha256: { pattern: "^[a-fA-F0-9]{64}$", type: "string" }
    },
    required: ["requestId", "sha256"],
    type: "object"
  },
  document_render: {
    additionalProperties: false,
    properties: {
      attach: { default: true, type: "boolean" },
      document_kind: { minLength: 1, type: "string" },
      filename: { minLength: 1, type: "string" },
      idempotency_key: { minLength: 1, type: "string" },
      owner_object_id: { minLength: 1, type: "string" },
      owner_object_type: { minLength: 1, type: "string" },
      site_id: { minLength: 1, type: "string" },
      template_id: { minLength: 1, type: "string" }
    },
    required: ["site_id", "owner_object_type", "owner_object_id"],
    type: "object"
  },
  // T5 (2026-09-16 annotate-bridge plan) — image_annotation_studio's three bridge verbs, captured
  // VERBATIM from the live per-tenant bridge's tools/list on 2026-09-16 (connector "Dr Lurie
  // Skincare", the same Platform bridge shape every tenant exposes). PLATFORM_TOOL_SCHEMAS_CAPTURED_AT
  // above is left untouched: these three entries were captured on 2026-09-16, the entries above were
  // not re-captured then, and stamping today's date over all of them would claim a freshness the rest
  // of this fixture does not have — the same note the T15.34 block above makes for its own additions.
  analyze_image_layout: {
    additionalProperties: false,
    properties: {
      public_path: { pattern: "^/(img|pdf)/[^/]+/[0-9a-fA-F]{64}\\.[a-z]+$", type: "string" },
      request_id: { minLength: 1, type: "string" },
      sha256: { pattern: "^[a-fA-F0-9]{64}$", type: "string" },
      site_id: { minLength: 1, type: "string" }
    },
    required: ["site_id", "request_id"],
    type: "object"
  },
  annotate_image: {
    additionalProperties: false,
    properties: {
      device_scale_factor: { type: "integer" },
      filename: { minLength: 1, type: "string" },
      format: { minLength: 1, type: "string" },
      idempotency_key: { minLength: 1, type: "string" },
      label: { minLength: 1, type: "string" },
      public_path: { pattern: "^/(img|pdf)/[^/]+/[0-9a-fA-F]{64}\\.[a-z]+$", type: "string" },
      quality: { type: "integer" },
      request_id: { minLength: 1, type: "string" },
      sha256: { pattern: "^[a-fA-F0-9]{64}$", type: "string" },
      site_id: { minLength: 1, type: "string" },
      slot: { minLength: 1, type: "string" },
      spec: { additionalProperties: true, type: "object" },
      tags: { items: { minLength: 1, type: "string" }, type: "array" }
    },
    required: ["site_id", "request_id", "spec"],
    type: "object"
  },
  check_image_text: {
    additionalProperties: false,
    properties: {
      expect: { items: { minLength: 1, type: "string" }, type: "array" },
      languages: { items: { minLength: 1, type: "string" }, type: "array" },
      mode: { enum: ["expect_none", "expect"], type: "string" },
      public_path: { pattern: "^/(img|pdf)/[^/]+/[0-9a-fA-F]{64}\\.[a-z]+$", type: "string" },
      request_id: { minLength: 1, type: "string" },
      sha256: { pattern: "^[a-fA-F0-9]{64}$", type: "string" },
      site_id: { minLength: 1, type: "string" }
    },
    required: ["site_id", "request_id", "mode"],
    type: "object"
  }
};
