import { listWorkspaceNodes, validateWorkspaceGraph } from "./nodes.js";
import type { WorkspaceNode, WorkspaceRiskLevel } from "./nodeTypes.js";

// §2.23 (handoff 2026-08-10): the publishing tail — contract_intelligence through learning_recorder —
// is ~46% of run cost and 100% of publish risk, and additional workflows (money_page, advertorial)
// are planned that must END in this exact sub-graph. If the tail were forked per workflow, every
// publish-gate fix would have to land N times forever, so it is extracted as ONE shared sub-graph
// BEFORE workflow #2 exists.
//
// This module is the single source of truth for the tail's SHAPE: its ordered node ids, its internal
// edges, and its upstream boundary. The canonical node LITERAL — prompts, schemas, tools, model
// config — stays in nodes.ts (generated by scripts/seedNodesFromWorkspace.ts; byte-stable under
// `npm run nodes:check`); everything else conforms to this declaration:
//
//   - tests/agent/workspace/publishingTail.test.ts fails CI if the canonical array's tail slice
//     drifts from this declaration, so a fork or silent rewire of the tail cannot land;
//   - scripts/seedNodesFromWorkspace.ts refuses a re-seed whose tail diverges from this declaration,
//     so a store-side topology edit cannot rewrite the tail unless this file changes in the same
//     commit — a deliberate, reviewed act;
//   - composeWorkflowNodes builds workflow #2 (and #N) as its own upstream + THIS tail, with the
//     boundary edges re-bound to that workflow's node ids, so every gate and fix that lands on the
//     tail lands once, for every workflow (src/agent/workspace/workflowRegistry.ts is the seam that
//     hands the composed array to the executor).
//
// T15.29 (2026-08-25, #205; ADR-2026-08-25-structure-studio §2.2) — every workflow composed through
// this seam ALSO inherits the copy/structure authority boundary, not just the publish tail's shape.
// "Only the studio (clone_conductor) authors structure" is declared ONCE, per workflowId, in
// publishableTypeCharter.ts's charter table, and enforced at three independent points: a static
// tool-permission audit over the composed node array (publishableTypeCharter.recipeAuthorityConformanceIssues),
// a publish-time type allowlist (that same charter, enforced in objectPublishExecution.buildObjectPublishPlan),
// and a runtime write guard in the emission transport
// (publishableTypeCharter.assertRecipeAuthorshipAllowed). A new workflow composed here gets all three
// for free by declaring its own row in that one charter table — it does not re-derive "who may author
// a recipe" locally, for the same reason it does not re-derive the publish gates themselves.

// The tail's node ids in canonical conductor order. This IS the shared sub-graph.
//
// T8 (Wave 3, 2026-08-13, run_1786557897658_elj34j): artifact_plan moved ahead of article_body. It
// used to run AFTER article_body and plan against a body that had already been built — so the only
// run this fix is named for shipped with zero media even though the run's envelope requested it:
// artifact_plan correctly found nothing to bind, because nothing had generated the artifact yet, and
// by the time it ran article_body had already finished without one. artifact_plan now depends on
// brief_architect (mediaSlots, the desired-media declaration) and contract_intelligence (the artifact
// protocol) instead of article_body, generates and verifies the artifact BEFORE the body is built, and
// article_body binds artifact_plan's verified references rather than planning its own media.
// W8 (2026-08-31): artifact_plan SPLITS. It keeps its id and becomes one tool-less model turn emitting
// materialization_spec.v1 (planning only), and the new deterministic artifact_materializer executes that
// spec — adopt/create/poll against the artifact bridge, no model turn — and emits the SAME
// artifact_plan.v1 the tail always carried. Everything T8 established about ordering is unchanged; what
// changed is that the polling is no longer bought at model prices. artifact_plan gains draft_writer as a
// dependency because a PDF slot's renderData is filled from the written prose (W9).
// T15.6 (2026-08-25, ADR-2026-08-25-publish-autonomy §4.3): release_executor lands after
// publish_executor and before learning_recorder — "publish_payload → publication_controller →
// publish_executor → release_executor → learning_recorder".
export const publishingTailNodeIds = [
  "contract_intelligence",
  "artifact_plan",
  "artifact_materializer",
  "article_body",
  "publish_payload",
  "publication_controller",
  "publish_executor",
  "release_executor",
  "learning_recorder"
] as const;

export type PublishingTailNodeId = typeof publishingTailNodeIds[number];

const tailIdSet = new Set<string>(publishingTailNodeIds);

export const isTailNode = (nodeId: string): nodeId is PublishingTailNodeId => tailIdSet.has(nodeId);

// T15.6 (ADR §6.1) — the tail's two segments. The AUTHORING segment is DTC copy authoring
// (contract_intelligence, artifact_plan, article_body) and is optional in composition: a capture or
// clone run has no article body and never will. The PUBLISH segment — publish_payload through
// learning_recorder, now including release_executor — is THE shared tail: mandatory for every workflow
// that publishes anything, not optional, not forkable, not substitutable. Both are exact partitions of
// publishingTailNodeIds (asserted at module load below), so composeWorkflowNodes's segment selector can
// never disagree with the drift guard about which node belongs to which segment.
export const publishingAuthoringSegmentIds = ["contract_intelligence", "artifact_plan", "artifact_materializer", "article_body"] as const;
export const publishingPublishSegmentIds = ["publish_payload", "publication_controller", "publish_executor", "release_executor", "learning_recorder"] as const;

const authoringIdSet = new Set<string>(publishingAuthoringSegmentIds);
const publishSegmentIdSet = new Set<string>(publishingPublishSegmentIds);

// Structural self-check: every tail node id belongs to EXACTLY one segment, and the two segments
// together cover the whole tail. A future tail-topology edit that forgets to update one of the three
// arrays fails here, at import time, rather than as a silent composition-time surprise.
{
  const uncovered = publishingTailNodeIds.filter((id) => !authoringIdSet.has(id) && !publishSegmentIdSet.has(id));
  const doubled = publishingTailNodeIds.filter((id) => authoringIdSet.has(id) && publishSegmentIdSet.has(id));
  if (uncovered.length || doubled.length) {
    throw new Error(`publishingTail segment partition drift: uncovered=[${uncovered.join(", ")}], in-both=[${doubled.join(", ")}]. publishingAuthoringSegmentIds and publishingPublishSegmentIds must exactly partition publishingTailNodeIds.`);
  }
}

// The declared shape of every tail node: full dependsOn/requiredInputs in canonical order (boundary
// and internal edges interleaved exactly as the canonical literal declares them), the artifact each
// node produces, and its risk classification. requiredInputs mirrors dependsOn for every tail node —
// that is a property of the current canonical set, and the conformance check pins it so it cannot
// drift apart silently.
export const publishingTailDeclaration: Record<PublishingTailNodeId, { dependsOn: readonly string[]; requiredInputs: readonly string[]; produces: readonly string[]; riskLevel: WorkspaceRiskLevel }> = {
  contract_intelligence: { dependsOn: ["brief_architect"], requiredInputs: ["brief_architect"], produces: ["contract_intelligence.v1"], riskLevel: "write" },
  artifact_plan: { dependsOn: ["brief_architect", "contract_intelligence", "draft_writer"], requiredInputs: ["brief_architect", "contract_intelligence", "draft_writer"], produces: ["materialization_spec.v1"], riskLevel: "read" },
  artifact_materializer: { dependsOn: ["artifact_plan", "contract_intelligence"], requiredInputs: ["artifact_plan", "contract_intelligence"], produces: ["artifact_plan.v1"], riskLevel: "write" },
  article_body: { dependsOn: ["review_aggregator", "draft_writer", "contract_intelligence", "narrative_movement", "angle_strategy", "artifact_materializer"], requiredInputs: ["review_aggregator", "draft_writer", "contract_intelligence", "narrative_movement", "angle_strategy", "artifact_materializer"], produces: ["client_object.v1"], riskLevel: "write" },
  publish_payload: { dependsOn: ["article_body", "artifact_materializer"], requiredInputs: ["article_body", "artifact_materializer"], produces: ["dry_run_publish_payload.v1"], riskLevel: "write" },
  publication_controller: { dependsOn: ["publish_payload"], requiredInputs: ["publish_payload"], produces: ["publication_decision.v1"], riskLevel: "publish" },
  publish_executor: { dependsOn: ["publication_controller"], requiredInputs: ["publication_controller"], produces: ["publish_execution.v1"], riskLevel: "publish" },
  release_executor: { dependsOn: ["publish_executor"], requiredInputs: ["publish_executor"], produces: ["release_execution.v1"], riskLevel: "publish" },
  learning_recorder: { dependsOn: ["publication_controller", "publish_executor", "release_executor"], requiredInputs: ["publication_controller", "publish_executor", "release_executor"], produces: ["learning_observations.v1"], riskLevel: "write" }
};

const deriveEdges = (keep: (dependency: string) => boolean): Record<PublishingTailNodeId, readonly string[]> => {
  const derived = {} as Record<PublishingTailNodeId, readonly string[]>;
  for (const nodeId of publishingTailNodeIds) derived[nodeId] = publishingTailDeclaration[nodeId].dependsOn.filter(keep);
  return derived;
};

// The tail's upstream boundary: for each tail node, the dependencies that live OUTSIDE the tail.
// These are the edges a second workflow re-binds to its own upstream node ids; everything else in
// dependsOn is tail-internal and identical in every workflow. Derived from the declaration so the
// boundary can never disagree with the declared edges.
export const publishingTailBoundary: Record<PublishingTailNodeId, readonly string[]> = deriveEdges((dependency) => !tailIdSet.has(dependency));

// The tail-internal edges — the complement of the boundary. Shared verbatim by every workflow.
export const publishingTailInternalEdges: Record<PublishingTailNodeId, readonly string[]> = deriveEdges((dependency) => tailIdSet.has(dependency));

// The upstream dependencies a tail node consumes, [] for a purely internal node. This is the "tail
// boundary" predicate: a workflow author asks tailBoundary("article_body") to learn which edges they
// must bind to their own upstream.
export const tailBoundary = (nodeId: string): readonly string[] => (isTailNode(nodeId) ? publishingTailBoundary[nodeId] : []);

// Every upstream node id the tail consumes under the default (publishing_conductor) binding, in
// first-appearance order: the tail's entry contract. brief_architect's article_brief.v1 (with its
// mediaSlots) feeds BOTH contract_intelligence and artifact_plan; draft_writer feeds artifact_plan
// (a PDF slot's renderData comes from the written prose); review_aggregator, draft_writer,
// narrative_movement and angle_strategy feed article_body.
export const publishingTailUpstreamIds: readonly string[] = [...new Set(publishingTailNodeIds.flatMap((nodeId) => publishingTailBoundary[nodeId]))];

const sameStringArray = (a: readonly string[], b: readonly string[]): boolean => a.length === b.length && a.every((value, index) => value === b[index]);

// Conformance of a node array's tail slice to this module's declaration. Empty array = conformant.
// Used by the drift-guard test (CI) and by scripts/seedNodesFromWorkspace.ts (re-seed refusal), so a
// tail fork is caught at both gates a topology change must pass.
export function publishingTailConformanceIssues(nodes: WorkspaceNode[]): string[] {
  const issues: string[] = [];
  const presentTailIds = nodes.filter((node) => isTailNode(node.id)).map((node) => node.id);
  for (const nodeId of publishingTailNodeIds) {
    const occurrences = presentTailIds.filter((id) => id === nodeId).length;
    if (occurrences === 0) issues.push(`Tail node missing: ${nodeId}`);
    else if (occurrences > 1) issues.push(`Tail node duplicated: ${nodeId}`);
  }
  if (!issues.length && !sameStringArray(presentTailIds, publishingTailNodeIds)) {
    issues.push(`Tail nodes out of declared order: found [${presentTailIds.join(", ")}], declared [${publishingTailNodeIds.join(", ")}]`);
  }
  for (const node of nodes) {
    if (!isTailNode(node.id)) continue;
    const declared = publishingTailDeclaration[node.id];
    if (!sameStringArray(node.dependsOn, declared.dependsOn)) issues.push(`Tail edge drift on ${node.id}: dependsOn [${node.dependsOn.join(", ")}] != declared [${declared.dependsOn.join(", ")}]`);
    if (!sameStringArray(node.requiredInputs, declared.requiredInputs)) issues.push(`Tail edge drift on ${node.id}: requiredInputs [${node.requiredInputs.join(", ")}] != declared [${declared.requiredInputs.join(", ")}]`);
    if (!sameStringArray(node.produces, declared.produces)) issues.push(`Tail artifact drift on ${node.id}: produces [${node.produces.join(", ")}] != declared [${declared.produces.join(", ")}]`);
    if (node.riskLevel !== declared.riskLevel) issues.push(`Tail risk drift on ${node.id}: riskLevel ${node.riskLevel} != declared ${declared.riskLevel}`);
  }
  return issues;
}

// A second workflow's binding of the tail boundary to its OWN upstream node ids. A tail node absent
// from the binding keeps its declared (publishing_conductor) boundary verbatim; a bound tail node's
// dependsOn becomes [boundUpstreamIds..., internalEdges...]. Purely-internal tail nodes need no entry.
export type PublishingTailBoundaryBinding = Partial<Record<PublishingTailNodeId, readonly string[]>>;

export class WorkflowCompositionError extends Error {
  readonly code = "invalid_workflow_composition";
  constructor(readonly issues: string[]) {
    super(`invalid_workflow_composition: ${issues.join("; ")}`);
  }
}

const copyNode = (node: WorkspaceNode): WorkspaceNode => ({ ...node, dependsOn: [...node.dependsOn], allowedTools: [...node.allowedTools], requiredInputs: [...node.requiredInputs], produces: [...node.produces], position: { ...node.position }, metadata: node.metadata ? { ...node.metadata } : undefined });

// Build a full workflow node array = upstream + the shared publishing tail, with the boundary edges
// bound to the upstream workflow's node ids. The tail node DEFINITIONS (prompt, schemas, tools,
// model config, riskLevel) come from the canonical set in nodes.ts, so every workflow shares one tail
// and a gate fixed there is fixed everywhere. Refuses (throws WorkflowCompositionError) rather than
// composing when: an upstream id collides with a tail id or repeats; a binding names a non-tail node
// or binds an edge to something that is not an upstream node; a tail node whose declared boundary is
// non-empty ends up with no upstream edge at all; or the composed graph fails validateWorkspaceGraph
// evaluated against itself as the run sequence.
//
// T15.6 (ADR §6.1) — which segments a composition includes. Default is the FULL tail (both segments),
// so every existing caller (composeWorkflowNodes(upstream) with no third argument) is unchanged and
// still reproduces the canonical array exactly. `publish: false` is refused outright when the upstream
// set can itself reach a publish verb (see PUBLISH_ONLY_VERBS below) — a workflow that can publish must
// compose the publish segment; there is no other sanctioned way for it to reach that verb.
export type PublishingTailSegmentSelection = { authoring?: boolean; publish?: boolean };
const DEFAULT_SEGMENTS: Required<PublishingTailSegmentSelection> = { authoring: true, publish: true };

// The two verbs a governed tail node may reach (object_publish via publish_executor,
// release_to_production via release_executor). An UPSTREAM node — anything the caller supplies, never
// a tail node — that can reach either of these while the publish segment is not composed is exactly
// the workflow-local publish/release path this ADR forbids (invariant 1): "a workflow-local publish or
// release mechanism is a defect, whatever its justification." Composition refuses it structurally.
const PUBLISH_ONLY_VERBS = new Set(["object_publish", "release_to_production"]);

// The tail node ids actually included for a given segment selection, in canonical order. Every tail id
// belongs to exactly one segment (asserted at module load above), so this partition is total.
const segmentTailIds = (selection: Required<PublishingTailSegmentSelection>): PublishingTailNodeId[] =>
  publishingTailNodeIds.filter((id) => (authoringIdSet.has(id) ? selection.authoring : selection.publish));

// The current workflow is expressible through this seam: composing the canonical upstream (every
// non-tail canonical node) with the default binding and the default (full-tail) segment selection
// reproduces the canonical array exactly — the drift-guard test asserts it.
export function composeWorkflowNodes(upstreamNodes: WorkspaceNode[], boundaryBinding: PublishingTailBoundaryBinding = {}, segments: PublishingTailSegmentSelection = {}): WorkspaceNode[] {
  const selection: Required<PublishingTailSegmentSelection> = { ...DEFAULT_SEGMENTS, ...segments };
  const issues: string[] = [];
  const upstreamIds = new Set<string>();
  for (const node of upstreamNodes) {
    if (isTailNode(node.id)) issues.push(`Upstream node id collides with a tail node: ${node.id}`);
    else if (upstreamIds.has(node.id)) issues.push(`Duplicate upstream node id: ${node.id}`);
    upstreamIds.add(node.id);
  }
  // The structural refusal (ADR §6.1): a workflow that publishes and does not compose the publish
  // segment fails composition, rather than silently omitting the tail's safety machinery.
  if (!selection.publish) {
    for (const node of upstreamNodes) {
      const reachable = node.allowedTools.filter((tool) => PUBLISH_ONLY_VERBS.has(tool));
      if (reachable.length) issues.push(`Upstream node ${node.id} can reach ${reachable.join(", ")} but the publish segment was not composed; a workflow that publishes must compose publishingPublishSegmentIds — there is no other sanctioned publish/release path.`);
    }
  }
  const includedTailIds = new Set<string>(segmentTailIds(selection));
  for (const [nodeId, bound] of Object.entries(boundaryBinding)) {
    if (!isTailNode(nodeId)) { issues.push(`Boundary binding names a non-tail node: ${nodeId}`); continue; }
    if (!includedTailIds.has(nodeId)) { issues.push(`Boundary binding names ${nodeId}, which is not part of the composed segment selection (authoring:${selection.authoring}, publish:${selection.publish})`); continue; }
    if (!bound) continue;
    for (const dependency of bound) {
      if (isTailNode(dependency)) issues.push(`Boundary binding for ${nodeId} points at a tail node: ${dependency} — tail-internal edges are fixed and never bound`);
      else if (!upstreamIds.has(dependency)) issues.push(`Unsatisfied boundary for ${nodeId}: ${dependency} is not in the upstream set`);
    }
  }
  const canonicalById = new Map(listWorkspaceNodes().map((node) => [node.id, node]));
  const tailNodes: WorkspaceNode[] = [];
  for (const nodeId of publishingTailNodeIds) {
    if (!includedTailIds.has(nodeId)) continue;
    const canonical = canonicalById.get(nodeId);
    if (!canonical) { issues.push(`Tail node missing from the canonical set: ${nodeId}`); continue; }
    // Boundary/internal are computed relative to the INCLUDED segment set, not the full tail: when a
    // node's declared dependency is excluded from this composition (e.g. publish_payload's article_body
    // edge, when the authoring segment is not composed), that dependency is no longer available
    // internally and becomes part of THIS node's boundary — exactly the seam capture/clone need to bind
    // publish_payload to their own emission/mint report (ADR §6.2), without this module needing to know
    // anything about capture or clone.
    const declaredDeps = publishingTailDeclaration[nodeId].dependsOn;
    const declaredBoundary = declaredDeps.filter((dependency) => !includedTailIds.has(dependency));
    const declaredInternal = declaredDeps.filter((dependency) => includedTailIds.has(dependency));
    const bound = boundaryBinding[nodeId];
    if (!bound) {
      // Unbound: the declared edges apply verbatim, restricted to what THIS composition includes —
      // for the default full-tail selection this reproduces the canonical array exactly.
      for (const dependency of declaredBoundary) {
        if (!upstreamIds.has(dependency)) issues.push(`Unsatisfied boundary for ${nodeId}: ${dependency} is not in the upstream set (bind it via boundaryBinding or add the upstream node)`);
      }
      tailNodes.push(copyNode(canonical));
      continue;
    }
    if (declaredBoundary.length && !bound.length) issues.push(`Boundary binding for ${nodeId} is empty, but its declared boundary [${declaredBoundary.join(", ")}] must be bound to at least one upstream node`);
    const rebound = copyNode(canonical);
    rebound.dependsOn = [...bound, ...declaredInternal];
    rebound.requiredInputs = [...bound, ...declaredInternal];
    tailNodes.push(rebound);
  }
  if (issues.length) throw new WorkflowCompositionError(issues);
  const composed = [...upstreamNodes.map(copyNode), ...tailNodes];
  // Validate the composed graph against ITSELF as the run sequence: unique ids, resolvable edges,
  // acyclic, requiredInputs satisfiable within this workflow, and the hard tail invariants.
  const validation = validateWorkspaceGraph(composed, composed);
  if (!validation.valid) throw new WorkflowCompositionError(validation.issues);
  return composed;
}
