import { listWorkspaceNodes, validateWorkspaceGraph } from "./nodes.js";
import type { WorkspaceNode, WorkspaceRiskLevel } from "./nodeTypes.js";

// §2.23 (handoff 2026-08-10): the publishing tail — contract_intelligence through learning_recorder —
// is ~46% of run cost and 100% of publish risk, and additional workflows (money_page, advertorial)
// are planned that must END in this exact sub-graph. If the tail were forked per workflow, every
// publish-gate fix would have to land N times forever, so it is extracted as ONE shared sub-graph
// BEFORE workflow #2 exists.
//
// This module is the single source of truth for the tail's SHAPE: its ordered node ids, its internal
// edges, and its upstream boundary. The canonical node LITERAL — prompts, schemas, tools, model
// config — stays in nodes.ts (generated by scripts/seedNodesFromWorkspace.ts; byte-stable under
// `npm run nodes:check`); everything else conforms to this declaration:
//
//   - tests/agent/workspace/publishingTail.test.ts fails CI if the canonical array's tail slice
//     drifts from this declaration, so a fork or silent rewire of the tail cannot land;
//   - scripts/seedNodesFromWorkspace.ts refuses a re-seed whose tail diverges from this declaration,
//     so a store-side topology edit cannot rewrite the tail unless this file changes in the same
//     commit — a deliberate, reviewed act;
//   - composeWorkflowNodes builds workflow #2 (and #N) as its own upstream + THIS tail, with the
//     boundary edges re-bound to that workflow's node ids, so every gate and fix that lands on the
//     tail lands once, for every workflow (src/agent/workspace/workflowRegistry.ts is the seam that
//     hands the composed array to the executor).

// The tail's node ids in canonical conductor order. This IS the shared sub-graph.
//
// T8 (Wave 3, 2026-08-13, run_1786557897658_elj34j): artifact_plan moved ahead of article_body. It
// used to run AFTER article_body and plan against a body that had already been built — so the only
// run this fix is named for shipped with zero media even though the run's envelope requested it:
// artifact_plan correctly found nothing to bind, because nothing had generated the artifact yet, and
// by the time it ran article_body had already finished without one. artifact_plan now depends on
// brief_architect (mediaSlots, the desired-media declaration) and contract_intelligence (the artifact
// protocol) instead of article_body, generates and verifies the artifact BEFORE the body is built, and
// article_body binds artifact_plan's verified references rather than planning its own media.
export const publishingTailNodeIds = [
  "contract_intelligence",
  "artifact_plan",
  "article_body",
  "publish_payload",
  "publication_controller",
  "publish_executor",
  "learning_recorder"
] as const;

export type PublishingTailNodeId = typeof publishingTailNodeIds[number];

const tailIdSet = new Set<string>(publishingTailNodeIds);

export const isTailNode = (nodeId: string): nodeId is PublishingTailNodeId => tailIdSet.has(nodeId);

// The declared shape of every tail node: full dependsOn/requiredInputs in canonical order (boundary
// and internal edges interleaved exactly as the canonical literal declares them), the artifact each
// node produces, and its risk classification. requiredInputs mirrors dependsOn for every tail node —
// that is a property of the current canonical set, and the conformance check pins it so it cannot
// drift apart silently.
export const publishingTailDeclaration: Record<PublishingTailNodeId, { dependsOn: readonly string[]; requiredInputs: readonly string[]; produces: readonly string[]; riskLevel: WorkspaceRiskLevel }> = {
  contract_intelligence: { dependsOn: ["brief_architect"], requiredInputs: ["brief_architect"], produces: ["contract_intelligence.v1"], riskLevel: "write" },
  artifact_plan: { dependsOn: ["brief_architect", "contract_intelligence"], requiredInputs: ["brief_architect", "contract_intelligence"], produces: ["artifact_plan.v1"], riskLevel: "write" },
  article_body: { dependsOn: ["review_aggregator", "draft_writer", "contract_intelligence", "narrative_movement", "angle_strategy", "artifact_plan"], requiredInputs: ["review_aggregator", "draft_writer", "contract_intelligence", "narrative_movement", "angle_strategy", "artifact_plan"], produces: ["client_object.v1"], riskLevel: "write" },
  publish_payload: { dependsOn: ["article_body", "artifact_plan"], requiredInputs: ["article_body", "artifact_plan"], produces: ["dry_run_publish_payload.v1"], riskLevel: "write" },
  publication_controller: { dependsOn: ["publish_payload"], requiredInputs: ["publish_payload"], produces: ["publication_decision.v1"], riskLevel: "publish" },
  publish_executor: { dependsOn: ["publication_controller"], requiredInputs: ["publication_controller"], produces: ["publish_execution.v1"], riskLevel: "publish" },
  learning_recorder: { dependsOn: ["publication_controller", "publish_executor"], requiredInputs: ["publication_controller", "publish_executor"], produces: ["learning_observations.v1"], riskLevel: "write" }
};

const deriveEdges = (keep: (dependency: string) => boolean): Record<PublishingTailNodeId, readonly string[]> => {
  const derived = {} as Record<PublishingTailNodeId, readonly string[]>;
  for (const nodeId of publishingTailNodeIds) derived[nodeId] = publishingTailDeclaration[nodeId].dependsOn.filter(keep);
  return derived;
};

// The tail's upstream boundary: for each tail node, the dependencies that live OUTSIDE the tail.
// These are the edges a second workflow re-binds to its own upstream node ids; everything else in
// dependsOn is tail-internal and identical in every workflow. Derived from the declaration so the
// boundary can never disagree with the declared edges.
export const publishingTailBoundary: Record<PublishingTailNodeId, readonly string[]> = deriveEdges((dependency) => !tailIdSet.has(dependency));

// The tail-internal edges — the complement of the boundary. Shared verbatim by every workflow.
export const publishingTailInternalEdges: Record<PublishingTailNodeId, readonly string[]> = deriveEdges((dependency) => tailIdSet.has(dependency));

// The upstream dependencies a tail node consumes, [] for a purely internal node. This is the "tail
// boundary" predicate: a workflow author asks tailBoundary("article_body") to learn which edges they
// must bind to their own upstream.
export const tailBoundary = (nodeId: string): readonly string[] => (isTailNode(nodeId) ? publishingTailBoundary[nodeId] : []);

// Every upstream node id the tail consumes under the default (publishing_conductor) binding, in
// first-appearance order: the tail's entry contract. brief_architect's article_brief.v1 (with its
// mediaSlots) feeds BOTH contract_intelligence and artifact_plan; review_aggregator, draft_writer,
// narrative_movement and angle_strategy feed article_body.
export const publishingTailUpstreamIds: readonly string[] = [...new Set(publishingTailNodeIds.flatMap((nodeId) => publishingTailBoundary[nodeId]))];

const sameStringArray = (a: readonly string[], b: readonly string[]): boolean => a.length === b.length && a.every((value, index) => value === b[index]);

// Conformance of a node array's tail slice to this module's declaration. Empty array = conformant.
// Used by the drift-guard test (CI) and by scripts/seedNodesFromWorkspace.ts (re-seed refusal), so a
// tail fork is caught at both gates a topology change must pass.
export function publishingTailConformanceIssues(nodes: WorkspaceNode[]): string[] {
  const issues: string[] = [];
  const presentTailIds = nodes.filter((node) => isTailNode(node.id)).map((node) => node.id);
  for (const nodeId of publishingTailNodeIds) {
    const occurrences = presentTailIds.filter((id) => id === nodeId).length;
    if (occurrences === 0) issues.push(`Tail node missing: ${nodeId}`);
    else if (occurrences > 1) issues.push(`Tail node duplicated: ${nodeId}`);
  }
  if (!issues.length && !sameStringArray(presentTailIds, publishingTailNodeIds)) {
    issues.push(`Tail nodes out of declared order: found [${presentTailIds.join(", ")}], declared [${publishingTailNodeIds.join(", ")}]`);
  }
  for (const node of nodes) {
    if (!isTailNode(node.id)) continue;
    const declared = publishingTailDeclaration[node.id];
    if (!sameStringArray(node.dependsOn, declared.dependsOn)) issues.push(`Tail edge drift on ${node.id}: dependsOn [${node.dependsOn.join(", ")}] != declared [${declared.dependsOn.join(", ")}]`);
    if (!sameStringArray(node.requiredInputs, declared.requiredInputs)) issues.push(`Tail edge drift on ${node.id}: requiredInputs [${node.requiredInputs.join(", ")}] != declared [${declared.requiredInputs.join(", ")}]`);
    if (!sameStringArray(node.produces, declared.produces)) issues.push(`Tail artifact drift on ${node.id}: produces [${node.produces.join(", ")}] != declared [${declared.produces.join(", ")}]`);
    if (node.riskLevel !== declared.riskLevel) issues.push(`Tail risk drift on ${node.id}: riskLevel ${node.riskLevel} != declared ${declared.riskLevel}`);
  }
  return issues;
}

// A second workflow's binding of the tail boundary to its OWN upstream node ids. A tail node absent
// from the binding keeps its declared (publishing_conductor) boundary verbatim; a bound tail node's
// dependsOn becomes [boundUpstreamIds..., internalEdges...]. Purely-internal tail nodes need no entry.
export type PublishingTailBoundaryBinding = Partial<Record<PublishingTailNodeId, readonly string[]>>;

export class WorkflowCompositionError extends Error {
  readonly code = "invalid_workflow_composition";
  constructor(readonly issues: string[]) {
    super(`invalid_workflow_composition: ${issues.join("; ")}`);
  }
}

const copyNode = (node: WorkspaceNode): WorkspaceNode => ({ ...node, dependsOn: [...node.dependsOn], allowedTools: [...node.allowedTools], requiredInputs: [...node.requiredInputs], produces: [...node.produces], position: { ...node.position }, metadata: node.metadata ? { ...node.metadata } : undefined });

// Build a full workflow node array = upstream + the shared publishing tail, with the boundary edges
// bound to the upstream workflow's node ids. The tail node DEFINITIONS (prompt, schemas, tools,
// model config, riskLevel) come from the canonical set in nodes.ts, so every workflow shares one tail
// and a gate fixed there is fixed everywhere. Refuses (throws WorkflowCompositionError) rather than
// composing when: an upstream id collides with a tail id or repeats; a binding names a non-tail node
// or binds an edge to something that is not an upstream node; a tail node whose declared boundary is
// non-empty ends up with no upstream edge at all; or the composed graph fails validateWorkspaceGraph
// evaluated against itself as the run sequence.
//
// The current workflow is expressible through this seam: composing the canonical upstream (every
// non-tail canonical node) with the default binding reproduces the canonical array exactly — the
// drift-guard test asserts it.
export function composeWorkflowNodes(upstreamNodes: WorkspaceNode[], boundaryBinding: PublishingTailBoundaryBinding = {}): WorkspaceNode[] {
  const issues: string[] = [];
  const upstreamIds = new Set<string>();
  for (const node of upstreamNodes) {
    if (isTailNode(node.id)) issues.push(`Upstream node id collides with a tail node: ${node.id}`);
    else if (upstreamIds.has(node.id)) issues.push(`Duplicate upstream node id: ${node.id}`);
    upstreamIds.add(node.id);
  }
  for (const [nodeId, bound] of Object.entries(boundaryBinding)) {
    if (!isTailNode(nodeId)) { issues.push(`Boundary binding names a non-tail node: ${nodeId}`); continue; }
    if (!bound) continue;
    if (publishingTailBoundary[nodeId].length && !bound.length) issues.push(`Boundary binding for ${nodeId} is empty, but its declared boundary [${publishingTailBoundary[nodeId].join(", ")}] must be bound to at least one upstream node`);
    for (const dependency of bound) {
      if (isTailNode(dependency)) issues.push(`Boundary binding for ${nodeId} points at a tail node: ${dependency} — tail-internal edges are fixed and never bound`);
      else if (!upstreamIds.has(dependency)) issues.push(`Unsatisfied boundary for ${nodeId}: ${dependency} is not in the upstream set`);
    }
  }
  const canonicalById = new Map(listWorkspaceNodes().map((node) => [node.id, node]));
  const tailNodes: WorkspaceNode[] = [];
  for (const nodeId of publishingTailNodeIds) {
    const canonical = canonicalById.get(nodeId);
    if (!canonical) { issues.push(`Tail node missing from the canonical set: ${nodeId}`); continue; }
    const bound = boundaryBinding[nodeId];
    if (!bound) {
      // Unbound: the declared (publishing_conductor) edges apply verbatim — including their declared
      // interleaving — so composing the canonical upstream reproduces the canonical array exactly.
      for (const dependency of publishingTailBoundary[nodeId]) {
        if (!upstreamIds.has(dependency)) issues.push(`Unsatisfied boundary for ${nodeId}: ${dependency} is not in the upstream set (bind it via boundaryBinding or add the upstream node)`);
      }
      tailNodes.push(copyNode(canonical));
      continue;
    }
    const rebound = copyNode(canonical);
    rebound.dependsOn = [...bound, ...publishingTailInternalEdges[nodeId]];
    rebound.requiredInputs = [...bound, ...publishingTailInternalEdges[nodeId]];
    tailNodes.push(rebound);
  }
  if (issues.length) throw new WorkflowCompositionError(issues);
  const composed = [...upstreamNodes.map(copyNode), ...tailNodes];
  // Validate the composed graph against ITSELF as the run sequence: unique ids, resolvable edges,
  // acyclic, requiredInputs satisfiable within this workflow, and the hard tail invariants.
  const validation = validateWorkspaceGraph(composed, composed);
  if (!validation.valid) throw new WorkflowCompositionError(validation.issues);
  return composed;
}
