// Site-credential scope lock — pins SITE_CLIENT_MANAGER_TOOLS against a committed artifact.
//
// WHY THIS EXISTS
//
// `SITE_CLIENT_MANAGER_TOOLS` (src/agent/capture/siteGenesis.ts) IS the per-tenant scoped bearer's
// `toolAllowlist`. Genesis mints every new site's credential from it, and
// `reconcileSiteClientManagerCredentials` re-mints EVERY existing tenant's credential from it too.
//
// It went stale once already: admin chat gained six workflow tools across PF4 and PF4b/D2a, nobody
// widened the constant, and live tenants kept 2-tool credentials — every workflow call 401'd, for
// weeks, with no signal, because nothing compared the constant to what admin chat actually needs. A
// credential rotation then made it worse: re-minting from the stale constant silently NARROWED a
// tenant whose bearer had been hand-widened to the correct scope.
//
// CI has no secrets and no network (see .github/workflows/ci.yml's header), so nothing here can call
// Secret Manager, Netlify, or a live Cloud Run Job to inspect what tenants actually hold. What this
// script CAN do — the same trick `test:drift`, `test:glossary`, and `test:objects` already use — is
// lock the SOURCE constant against a checked-in artifact, so a change to it can never land silently:
// touching the allowlist without regenerating the lock is a reviewable, failing diff.
//
// This is a source-level lock, not a live-fleet check. Matching the lock only proves the CONSTANT
// hasn't drifted since it was last regenerated; it says nothing about whether every tenant's minted
// credential still reflects it. That is what the reconciler job is for — see the note below.
//
// Usage:
//   npm run test:scope        check the checked-in lock matches SITE_CLIENT_MANAGER_TOOLS (exit 1 on drift)  <- CI
//   npm run scope:update      regenerate docs/site-credential-scope-lock.json                                <- intentional scope change

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { SITE_CLIENT_MANAGER_TOOLS } from "../src/agent/capture/siteGenesis.js";

const OUTPUT = join(process.cwd(), "docs/site-credential-scope-lock.json");

export type ScopeLock = {
  version: "site_client_manager_tools_lock.v1";
  note: string;
  toolCount: number;
  tools: string[];
};

const NOTE =
  "Generated by scripts/siteCredentialScopeLock.ts. Locks SITE_CLIENT_MANAGER_TOOLS " +
  "(src/agent/capture/siteGenesis.ts) — the exact toolAllowlist genesis mints into every new site's " +
  "scoped bearer, and the allowlist reconcileSiteClientManagerCredentials re-mints EVERY existing " +
  "tenant's credential from. Regenerate deliberately with `npm run scope:update` when the allowlist " +
  "intentionally changes, and when you do: this file changing is not enough on its own — every " +
  "already-registered tenant is still running on the OLD scope until someone re-runs the " +
  "`site-credential-reconciler` Cloud Run Job with `--apply` (see docs/mcp-scoped-bearer-auth.md). " +
  "Widening the constant without that rotation just changes what NEW sites get; narrowing it without " +
  "warning the fleet is how a tenant's working workflow call turns into a silent 401.";

export const buildScopeLock = (tools: readonly string[]): ScopeLock => ({
  version: "site_client_manager_tools_lock.v1",
  note: NOTE,
  toolCount: tools.length,
  tools: [...tools]
});

export const renderScopeLock = (tools: readonly string[]): string => `${JSON.stringify(buildScopeLock(tools), null, 2)}\n`;

const main = () => {
  const rendered = renderScopeLock(SITE_CLIENT_MANAGER_TOOLS);
  const write = process.argv.includes("--write");

  if (write) {
    writeFileSync(OUTPUT, rendered, "utf8");
    console.log(`scope lock        written  ${SITE_CLIENT_MANAGER_TOOLS.length} tools -> docs/site-credential-scope-lock.json`);
    return;
  }

  let current: string;
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    console.error("scope lock        MISSING  docs/site-credential-scope-lock.json does not exist. Run `npm run scope:update`.");
    process.exit(1);
    return;
  }

  if (current === rendered) {
    console.log(`scope lock        ok       docs/site-credential-scope-lock.json matches SITE_CLIENT_MANAGER_TOOLS (${SITE_CLIENT_MANAGER_TOOLS.length} tools)`);
    return;
  }

  let locked: ScopeLock | undefined;
  try {
    locked = JSON.parse(current) as ScopeLock;
  } catch {
    // Fall through with locked left undefined — the raw-text diff below still reports something useful.
  }

  console.error("scope lock        DRIFT    SITE_CLIENT_MANAGER_TOOLS no longer matches docs/site-credential-scope-lock.json.");
  if (locked && Array.isArray(locked.tools)) {
    const lockedSet = new Set(locked.tools);
    const liveSet = new Set<string>(SITE_CLIENT_MANAGER_TOOLS);
    const added = SITE_CLIENT_MANAGER_TOOLS.filter((tool) => !lockedSet.has(tool));
    const removed = locked.tools.filter((tool) => !liveSet.has(tool));
    for (const tool of added) console.error(`                           + added:   ${tool}`);
    for (const tool of removed) console.error(`                           - removed: ${tool}`);
  }
  console.error("                           The constant is the source of truth; the lock file is generated from it.");
  console.error("                           If this scope change is intentional:");
  console.error("                             1. npm run scope:update   (regenerates the lock; commit it)");
  console.error("                             2. Re-run the `site-credential-reconciler` Cloud Run Job with --apply,");
  console.error("                                or every already-registered tenant stays on the old scope.");
  process.exit(1);
};

main();
